mysite/myauth/urls.py
from django.urls import path
from .views import (login_view,
                    get_cookie_view,
                    set_cookie_view,
                    set_session_view,
                    get_session_view,
                    logout_view,
                    AboutMeView,
                    RegisterView,
                    FooBarView,
                    edit_avatar_view,
                    user_list_view,
                    user_detail_view,
                    HelloView,
                    )
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'myauth'


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='myauth/login.html', redirect_authenticated_user=True
    ),
         name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('cookie/get', get_cookie_view, name='cookie-get'),
    path('cookie/set', set_cookie_view, name='cookie-set'),
    path('session/set', set_session_view, name='session-set'),
    path('session/get', get_session_view, name='session-get'),
    path('logout/', logout_view, name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('about-me/edit-avatar/<int:pk>/', edit_avatar_view, name='edit-avatar'),
    path('register/', RegisterView.as_view(), name='register'),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
    path('users/', user_list_view, name='user-list'),
    path('users/<int:pk>/', user_detail_view, name='user-detail'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.static import settings
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name='redoc',),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

mysite/shopapp/urls.py
from django.views.decorators.cache import cache_page
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.contrib.sitemaps.views import sitemap
from .views import (
    ShopIndexView,
    GroupsListView, ProductsListView, OrdersListView, create_product,
    create_order, ProductsDetailsView, OrderDetailView, ProductCreateView,
    ProductUpdateView, ProductDeleteView, OrderUpdateView, OrderDeleteView,
    ProductsDataExportView, OrdersDataExportView, ProductViewSet, OrderViewSet, LatestProductsFeed, UserOrdersListView,
    UserOrdersExportView,
)
from .sitemap import ProductSitemap, OrderSitemap

app_name = 'shopapp'

sitemaps = {
    'products': ProductSitemap,
    'orders': OrderSitemap,
}

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('api/', include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products_export'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductsDetailsView.as_view(), name='products_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='products_update'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='products_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
    path('orders/create/', create_order, name='order_create'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='orders_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='orders_delete'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders_export'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('products/latest/feed/', LatestProductsFeed(), name='products_latest_feed'),
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='users_orders_list'),
    path('users/<int:user_id>/orders/export/', UserOrdersExportView.as_view(), name='user_orders_export'),
]

mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

def product_preview_directory_path(instance:'Product', filename: str):
    return 'products/product_{pk}/preview/{filename}'.format(pk=instance.pk, filename=filename)


class Product(models.Model):
    """
    Модель Product представляет товар, который можно продавать в интернет-магазине
    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='products')
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)


    # class Meta:
    #     ordering = ['-price']
    #
    # @property
    # # def description_short(self):
    # #     if len(self.description) < 48:
    # #         return self.description
    # #     return self.description[:48] + '...'

    def __str__(self):
        return f'Product: (pk={self.pk}, name={self.name!r})'

    def get_absolute_url(self):
        return reverse('shopapp:products_details', kwargs={'pk': self.pk})

def product_images_directory_path(instance:'Product', filename: str):
    return 'products/product_{pk}/images/{filename}'.format(pk=instance.product.pk, filename=filename)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=255, null=False, blank=True)




class Order(models.Model):
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20,null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    product = models.ManyToManyField(Product,related_name='orders')
    phone_number = models.CharField(max_length=20,null=False, blank=True)
    receipt = models.FileField(null=True, upload_to='orders/receipts')

    def get_absolute_url(self):
        return reverse('shopapp:order_details', kwargs={'pk': self.pk})

    def __str__(self):
        return f'Order {self.pk} by {self.user}'

mysite/shopapp/views.py
"""В этом модуле лежат различные представления для интернет-магазина. По товарам заказам, и т д."""

import logging
from csv import DictWriter

from django.contrib.auth.models import Group, User
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404, reverse
from django.views.decorators.cache import cache_page

from .models import Product, Order, ProductImage
from .forms import ProductForm, OrderForm, GroupForm
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.syndication.views import Feed
from django.core.cache import cache
from .forms import ProductForm
from rest_framework.viewsets import ModelViewSet
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser
from .common import save_csv_products




log=logging.getLogger(__name__)

class ShopIndexView(View):
    # @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest):
        products = [
            ("orange", 1),
            ('banana', 2),
            ('apple', 3),
        ]

        context = {
            'products': products,
            'items': 2,
        }
        print('shop index context', context)
        return render(request, 'shopapp/shop-index.html', context=context)

@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.
    Полный CRUD для сущностей товара

    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter, DjangoFilterBackend, OrderingFilter,
    ]
    search_fields = ['name', 'description']
    permission_classes = [IsAuthenticated]
    filterset_fields = ['name',
                        'description',
                        'price',
                        'discount',
                        'archived',
                        ]
    ordering_fields = [
        'name',
        'price',
        'discount',
    ]
    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        # print('Hello products list')
        return super().list(*args, **kwargs)


    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)
    @extend_schema(
        summary='Get one product by id',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Empty response, product by id not found'),
        }

    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=['get'],detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')
        filename = 'products-export.csv'
        response['Content-Disposition'] = f'attachment; filename={filename}'
        queryset = self.filter_queryset(self.get_queryset())
        fields = ['name', 'description', 'price', 'discount']
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })

        return response

    @action(methods=['post'],detail=False, parser_classes=[MultiPartParser])
    def upload_csv(self,request: Request):
        products = save_csv_products(
            request.FILES['file'].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter,
        SearchFilter,
    ]
    filterset_fields = ['user',
                        'product',
                        'phone_number',
                        ]
    ordering_fields = ['user',
                       'product',
                       'phone_number',
                       ]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)




class GroupsListView(View):
    def get(self, request: HttpRequest):
        context = {
            'form': GroupForm(),
            'groups': Group.objects.all()

        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductsDetailsView(DetailView):
    # model = Product
    queryset = Product.objects.prefetch_related('images')
    template_name = 'shopapp/products-details.html'
    context_object_name = 'product'


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


def create_product(request: HttpRequest):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            url = reverse('shopapp:products_list')
            return redirect(url)
    else:
        form = ProductForm()
    context = {
        'form': form
    }

    return render(request, 'shopapp/create-product.html', context=context)


def create_order(request: HttpRequest):
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            url = reverse('shopapp:orders_list')
            return redirect(url)
    else:
        form = OrderForm()

    context = {
        'form': form
    }

    return render(request, 'shopapp/create-order.html', context=context)


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    fields = ['name', 'price', 'description', 'discount', 'preview']
    success_url = reverse_lazy('shopapp:products_list')

    permission_required = 'shopapp.add_product'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class OrdersListView(LoginRequiredMixin, ListView):
    template_name = 'shopapp/order_list.html'
    model = Order
    context_object_name = 'orders'
    success_url = reverse_lazy('shopapp:products_list')


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name_suffix = "_update_form"

    def test_func(self):
        product = self.get_object()
        user = self.request.user
        return user.is_superuser or (user == product.created_by and user.has_perm('shopapp.change_product'))

    def get_success_url(self):
        return reverse('shopapp:products_details', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.FILES.getlist('images'):
            for image in self.request.FILES.getlist('images'):
                ProductImage.objects.create(product=self.object, image=image)
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrderDetailView(PermissionRequiredMixin, DetailView):
    model = Order
    template_name = 'shopapp/order_detail.html'
    permission_required = 'shopapp.view_order'


class OrderUpdateView(UpdateView):
    model = Order
    fields = 'user', 'delivery_address', 'product', 'phone_number'
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            'shopapp:order_details',
            kwargs={'pk': self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:orders_list')


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = 'products_data_export'
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by('pk').all()
            products_data = [{
                'pk': product.pk,
                'name': product.name,
                'price': product.price,
                'archived': product.archived,
            }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
        return JsonResponse({'products': products_data})


class OrdersDataExportView(View):
    def get(self, request, *args, **kwargs):
        orders = Order.objects.all()
        expected_data = [
            {
                'id': order.id,
                'address': order.delivery_address,
                'promocode': order.promocode,
                'user_id': order.user.id,
                'product_ids': [product.id for product in order.product.all()],

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base Body
    {% endblock %}
</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Create Order
{% endblock %}

{% block body %}
	<h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Create Product
{% endblock %}

{% block body %}

	<h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
    {% if not groups %}
        <h3>No groups yet</h3>
    {% else %}
        <ul>
        {% for group in groups %}
        	<li>
                <div><strong>{{ group.name }}</strong></div>
                <ul>
                    {% for permission in group.permissions.all %}
                        <li>{{ permission.name }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Confirm delite {{ object.name }}
{% endblock %}
{% block body %}
    <h1>Delete {{ object.pk }} order?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit'> Delete</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
        {% for order in object_list %}
            <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
            >Details #{{ order.pk }}</a></p>
            <div>
            <p>Order by {% firstof order.user.first_name order.user.username %}</p>
            <p>Phone number: <code>{{ order.phone_number }}</code></p>
            <p>Promocode: <code>{{ order.promocode }}</code></p>
            <p>Delivery address: {{ order.delivery_address }}</p>
            <div>
                Products in order:
                <ul>
                    {% for product in order.product.all %}
                        <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}
                </ul>
            </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Update Order
{% endblock %}

{% block body %}
	<h1>Update a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}
            <button type="submit">
                Update
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">
            Back to orders #{{ object.pk }}
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Confirm archive {{ object.name }}
{% endblock %}
{% block body %}
    <h1>Archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:products_details' pk=object.pk %}"
        >Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit'> Archived</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Crate Product
{% endblock %}

{% block body %}
    <h1>Create Product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}"
        >Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Product' %} {{ product.pk }}
{% endblock %}

{% block body %}
    <h1>{% translate 'Product' %}: <strong>{{ product.name }}</strong></h1>

    <div>
        {% blocktranslate with description=product.description price=product.price discount=product.discount archived=product.archived %}
            <div>Description: <em>{{ description }}</em></div>
            <div>Price: {{ price }}</div>
            <div>Discount: {{ discount }}%</div>
            <div>Archived: {{ archived }}</div>
        {% endblocktranslate %}
    </div>

    {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}

    <h3>{% translate 'Images' %}:</h3>
    <div>
        {% blocktranslate count image_count=product.images.count %}
            There is {{ image_count }} image available.
        {% plural %}
            There are {{ image_count }} images available.
        {% endblocktranslate %}
    </div>

    <div>
        {% for image in product.images.all %}
            <div>
                <img src="{{ image.image.url }}" alt="{{ image.image.name }}">
                <div>{{ image.description }}</div>
            </div>
        {% empty %}
            <div>{% translate 'No images uploaded yet' %}</div>
        {% endfor %}
    </div>

    <div>
        <a href="{% url 'shopapp:products_update' pk=product.pk %}">{% translate 'Update product' %}</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_delete' pk=product.pk %}">{% translate 'Archive product' %}</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">{% translate 'Go back to products list' %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Products List' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
        {% blocktranslate count products_count=products|length %}
            There is only one product.
            {% plural %}
            there are {{ products_count }} products.
        {% endblocktranslate %}
        </div>
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url 'shopapp:products_details' product.pk %}"
                    >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
                    <p>{% translate 'Price' %}: {{ product.price }}</p>
                    {% translate 'No discount' as no_discount %}
                    <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
                </div>

                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}

            {% endfor %}
        </div>
    {% else %}
        {% url 'shopapp:product_create' as create_product_url%}
        {% blocktranslate %}
            <h3>No products yet</h3>
            <a href="{{ create_product_url }}">
                Create a new one
            </a>
        {% endblocktranslate %}
    {% endif %}

    <div>
        {% if perms.shopapp.add_product %}
            <a href="{% url 'shopapp:product_create' %}">
                {% translate 'Create a new product' %}
            </a>
        {% else %}
            <p>{% translate 'You do not have permission to create a product.' %}</p>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
	<li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink"
        >Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop index

{% endblock %}


{% block body %}
    <h1> Hello!</h1>
    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} {{ name|length }} for ${{ price }}</li>
                {% if name|length_is:'6' %}
                    <span>Lucky product</span>
                {% endif %}
            {% endfor %}
        </ul>
    </div>

    {% cache 100 lorem %}
    <div>
        {% lorem 3 p random %}
    </div>
    {% endcache %}

    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:'y,ies' }}
        </strong>
    </div>


{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}
{% block title %}
    <h1>User orders</h1>
{% endblock %}

{% block body %}
    <div>
        <p>Orders from user {{ owner.first_name }} {{ owner.last_name }} ({{ owner.username }})</p>
        {% cache 600 "orders_list_for_user_"|add:owner.pk %}
        {% if orders %}
            <ul>
                {% for order in orders %}
                    <li>Order #{{ order.id }}: {{ order.product.name }} ({{ order.delivery_address }})</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>User doesn't have any orders yet</p>
        {% endif %}
        {% endcache %}
    </div>
{% endblock %}