mysite/myauth/urls.py
from django.urls import path
from .views import (login_view,
                    get_cookie_view,
                    set_cookie_view,
                    set_session_view,
                    get_session_view,
                    logout_view,
                    AboutMeView,
                    RegisterView,
                    FooBarView,
                    edit_avatar_view,
                    user_list_view,
                    user_detail_view,
                    HelloView,
                    )
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'myauth'


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='myauth/login.html', redirect_authenticated_user=True
    ),
         name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('cookie/get', get_cookie_view, name='cookie-get'),
    path('cookie/set', set_cookie_view, name='cookie-set'),
    path('session/set', set_session_view, name='session-set'),
    path('session/get', get_session_view, name='session-get'),
    path('logout/', logout_view, name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('about-me/edit-avatar/<int:pk>/', edit_avatar_view, name='edit-avatar'),
    path('register/', RegisterView.as_view(), name='register'),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
    path('users/', user_list_view, name='user-list'),
    path('users/<int:pk>/', user_detail_view, name='user-detail'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.static import settings
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name='redoc',),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver




def product_images_directory_path(instance:'User', filename: str):
    return 'users/user_{pk}/images/{filename}'.format(pk=instance.user.pk, filename=filename)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_exepted = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=product_images_directory_path, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mysite/myauth/forms.py
from django import forms
from .models import Profile

class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']

mysite/myauth/views.py
from random import random
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required,permission_required,user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.contrib import messages
from django.http import HttpResponse, HttpRequest, JsonResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Profile
from django.views import View
from .forms import AvatarForm
from django.views.generic import TemplateView, CreateView
from django.utils.translation import gettext_lazy as _, ngettext
from django.views.decorators.cache import cache_page




class HelloView(View):
    welcome_message = _('Welcome hello world!')
    def get(self, request):
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            'one product',
            '{count} products',
            items,
        )
        products_line =  products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"

        )

class AboutMeView(TemplateView):
    template_name = 'myauth/about-me.html'

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        user = authenticate(self.request, username=username, password=password,)
        login(self.request, user)
        return response


def login_view(request:HttpRequest):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/admin')

        return render(request, 'myauth/login.html')

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin')

    return render(request, 'myauth/login.html', {'error': 'Invalid username or password'})

# @user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request:HttpRequest):
    response = HttpResponse("Cookies set")
    response.set_cookie('fizz','buzz', max_age=3600)
    return response
@cache_page(60 * 2)
def get_cookie_view(request:HttpRequest):
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f'Cookie value: {value!r} + {random()}')
@permission_required('myauth.view_profile', raise_exception=True)
def set_session_view(request:HttpRequest):
    request.session['foobar'] = 'spameggs'
    return HttpResponse('Session set')

@login_required
def get_session_view(request:HttpRequest):
    value = request.session.get('foobar', 'default value')
    return HttpResponse(f'Session value: {value!r}')

def logout_view(request:HttpRequest):
    logout(request)
    return redirect(reverse('myauth:login'))

# class MyLogoutView(LogoutView):
#     next_page = reverse_lazy('myauth:login')
#
#     def get(self, request, *args, **kwargs):
#         return self.post(request, *args, **kwargs)


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo':'bar', 'spam':'eggs'})


@login_required
def edit_avatar_view(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    if request.user != profile.user and not request.user.is_staff:
        return HttpResponseForbidden("You are not allowed to edit this profile.")
    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Avatar updated successfully!')
            return redirect('myauth:user-detail', pk=profile.user.pk)
    else:
        form = AvatarForm(instance=profile)

    return render(request, 'myauth/edit_avatar.html', {'form': form})


def user_list_view(request):
    users = User.objects.all()
    return render(request, 'myauth/user_list.html', {'users': users})

def user_detail_view(request, pk):
    user = get_object_or_404(User, pk=pk)
    return render(request, 'myauth/user_detail.html', {'user': user})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}About Me{% endblock %}

{% block body %}
    <h1>User Info</h1>
    {% if user.is_authenticated %}
        {% cache 300 userinfo user.username %}
            <h2>Detail</h2>
            <p>Username: {{ user.username }}</p>
            <p>First name: {{ user.first_name }}</p>
            <p>Last name: {{ user.last_name }}</p>
            <p>Email: {{ user.email }}</p>
        {% endcache %}
        {% if user.profile %}
            <p>Bio: {{ user.profile.bio }}</p>
            <h1>Avatar</h1>

            <a href="{% url 'myauth:edit-avatar' user.profile.pk %}">Edit Avatar</a>

            {% if user.profile.avatar and user.profile.avatar.url %}
                <img src="{{ user.profile.avatar.url }}" alt="User Avatar">
            {% else %}
                <p>No avatar</p>
            {% endif %}
        {% else %}
            <p>Bio: No bio available.</p>
        {% endif %}
    {% else %}
        <p>You are not logged in.</p>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/edit_avatar.html
{% extends 'myauth/base.html' %}

{% block title %}Edit Avatar{% endblock %}

{% block body %}
    <h1>Edit Avatar</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
<a href="{% url 'myauth:about-me'  %}">Back to profile</a>
{% endblock %}

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit"> Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user_detail.html
{% extends 'myauth/base.html' %}

{% block title %}User Detail{% endblock %}

{% block body %}
    <h1>{{ user.username }}'s Profile</h1>
    <p>Email: {{ user.email }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="User Avatar">
    {% else %}
        <p>No avatar available</p>
    {% endif %}

    {% if user == request.user or request.user.is_staff %}
        <a href="{% url 'myauth:edit-avatar' user.profile.pk %}">Edit Avatar</a>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/user_list.html
{% extends 'myauth/base.html' %}

{% block title %}User List{% endblock %}

{% block body %}
    <h1>User List</h1>
    <ul>
        {% for user in users %}
            <li><a href="{% url 'myauth:user-detail' user.pk %}">{{ user.username }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}